services:
  - type: web
    name: ai-web-scraper-api
    runtime: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      playwright install chromium
      playwright install-deps
    startCommand: |
      uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: ENVIRONMENT
        value: "production"
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: "/opt/render/project/.cache/ms-playwright"
    autoDeploy: true
    healthCheckPath: /health