services:
  - type: web
    name: ai-web-scraper-api
    runtime: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: |
      uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: PORT
        value: "10000"
      - key: ENVIRONMENT
        value: "production"
    autoDeploy: true
    healthCheckPath: /health